### ISSUE TITLE
IndexError: string index out of range when using extract_kraken_reads

### ISSUE THREAD

**Issue by fetyj** [jenniferlu717/KrakenTools#101]
Hi,
I'm getting this error when using extract_kraken_reads.py, could you help me solve this error?
```
python /home/ga-fr-noy-linux02/KrakenTools-1.2/extract_kraken_reads.py -s1 cseqs_1.fq -s2 cseqs_2.fq -o phimixphages15_1.fq -o2 phimixphages15_2.fq --fastq-output -k BAPH15 -t 10239 --include-children -r S7410_phi882-25_phi143BolivieA
PROGRAM START TIME: 11-25-2024 09:25:12
>> STEP 0: PARSING REPORT FILE S7410_phi882-25_phi143BolivieA
Traceback (most recent call last):
  File "/home/ga-fr-noy-linux02/KrakenTools-1.2/extract_kraken_reads.py", line 433, in <module>
    main()
  File "/home/ga-fr-noy-linux02/KrakenTools-1.2/extract_kraken_reads.py", line 230, in main
    num = int(prev_node.level_id[-1]) + 1
              ~~~~~~~~~~~~~~~~~~^^^^
IndexError: string index out of range
```
Best regards,
FJ

**Comment by vincebaby6** [comment]
Hello FJ,

I recently got the same kind of error and it would seem that it happens when there is missing data in the taxonomic level column (the one with R, K, D, P, etc.) in the Kraken report. As an example, the second line indicating ''cellular organisms'' was missing the ''R1'' value in the column. Krakentools is not able to manage an empty value in that position with the ''root'' as the only exception.  It is still not clear to me if this missing data is intentionnal in the latest version of Kraken2 and that krakentools simply did not keep up with those updates. It is also not clear to me if the data may be missing from the database itself, I used a pre-made database since I could not build it on my system due to administrative restrictions (don't ask...). I'm still looking into a solution and I'll post something here if I find a good workaround.

Regards,

Vincent

**Comment by fetyj** [comment]
Hello Vincent,
Thanks for your hint on this issue. Hope you can find out something, I'm trying to bypass it using the ```--append``` option and proceeding rank by rank on the taxonomy.
Best regards,
FJ

**Comment by fetyj** [comment]
Hello Vincent,
Thanks for the tip, it worked also for my data :) I checked on the kraken2 github issue and found this one that is related to this case (https://github.com/DerrickWood/kraken2/issues/888#issue-2652588907). Going back to kraken2 v2.0.8 solve the problem.
Best Regards,

FJ
